// SpiritualShaadi - Mock Profiles Database
const mockProfiles = [
  {
    id: "sp-1",
    name: "Aarav Sharma",
    age: 28,
    gender: "Male",
    height: "5'11\"",
    location: "Vrindavan, UP",
    religion: "Hinduism",
    sect: "Vaishnavism",
    caste: "Brahmin",
    subcaste: "Saraswat",
    spiritualPath: "ISKCON (Krishna Consciousness)",
    deity: "Lord Krishna",
    sadhana: "Chanting 16 rounds of Hare Krishna Mahamantra, daily Bhagavad Gita reading, and attending morning Mangala Aarti.",
    diet: "Strict Sattvic Vegetarian (No Onion/Garlic/Mushroom)",
    profession: "Remote Software Architect",
    avatarColor: "from-orange-400 to-amber-600",
    bio: "Seeking a devotee soulmate to serve Shri Vrindavan Dham together. Daily sadhana, chanting, and scriptural study are the cornerstones of my life. I love kirtan and devotional music.",
    hobbies: ["Kirtan Singing", "Playing Mridanga", "Vedic Literature", "Gau Seva (Cow care)"],
    chatGreeting: "Hare Krishna! 🙏 Placed in the services of Sri Radha Shyamsundar. How is your spiritual journey progressing?",
    chatResponses: [
      "For me, spiritual connection is the foundation of marriage. Sharing early morning sadhana builds a divine bond.",
      "Yes, I visit the temple daily. Listening to Kartika kirtan is incredibly nourishing for the soul.",
      "I work remotely, which allows me to stay in the holy vibe of Vrindavan. What are your thoughts on simple living and high thinking?",
      "Chanting helps me find deep peace amidst a hectic day. I would love to share a path of devotional service with my partner."
    ]
  },
  {
    id: "sp-2",
    name: "Ananya Iyer",
    age: 26,
    gender: "Female",
    height: "5'5\"",
    location: "Coimbatore, Tamil Nadu",
    religion: "Hinduism",
    sect: "Shaivism",
    caste: "Brahmin",
    subcaste: "Smartha Iyer",
    spiritualPath: "Isha Foundation (Inner Engineering)",
    deity: "Lord Shiva (Adiyogi)",
    sadhana: "Daily Shambhavi Mahamudra Kriya, Surya Kriya, and regular silent meditations.",
    diet: "Lacto-Vegetarian",
    profession: "Yoga Instructor & Wellness Coach",
    avatarColor: "from-purple-500 to-indigo-600",
    bio: "Deeply connected to the path of self-realization, inner engineering, and yogic science. I believe marriage is an acceleration of two seekers towards ultimate liberation.",
    hobbies: ["Hatha Yoga", "Classical Carnatic Music", "Trekking", "Organic Gardening"],
    chatGreeting: "Pranam! 🙏 Connecting with the Adiyogi within. I hope you are having a peaceful and conscious day.",
    chatResponses: [
      "Shambhavi has completely transformed my perspective. It brings a profound sense of inner clarity.",
      "I love spending time at the Dhyanalinga dome. The energetic stillness there is beyond words.",
      "A conscious partner who understands that we are first and foremost spiritual beings is what I pray for.",
      "Daily yoga keeps my system balanced. Do you practice any form of meditation or energy work?"
    ]
  },
  {
    id: "sp-3",
    name: "Meher Bukhari",
    age: 29,
    gender: "Female",
    height: "5'9\"",
    location: "New Delhi, Delhi",
    religion: "Islam",
    sect: "Sufism",
    caste: "Syed",
    subcaste: "Chishti Murid",
    spiritualPath: "Hazrat Nizamuddin Sufi Order",
    deity: "The Divine (Allah - Al-Wadud)",
    sadhana: "Five times Namaaz, daily Sufi Dhikr (remembrance), reading Rumi and Hafiz mystical poetry, and serving the needy.",
    diet: "Halal Non-Vegetarian",
    profession: "Sufi Calligrapher & Historical Archivist",
    avatarColor: "from-emerald-400 to-teal-600",
    bio: "A seeker of Divine Love (Ishq-e-Haqiqi). I look at the world through the lens of mysticism and calligraphy. Seeking a companion who values absolute sincerity and inner beauty.",
    hobbies: ["Calligraphy", "Urdu Poetry", "Playing the Ney (Flute)", "Historical Preservation"],
    chatGreeting: "Salaam and blessings of peace. 🌹 'Let the beauty of what you love be what you do.' How is your heart today?",
    chatResponses: [
      "Sufism is the path of polishing the mirror of the heart. Love is the ultimate religion of the soul.",
      "I spend my Thursdays listening to the soulful Qawwalis at the Nizamuddin Dargah. It is pure spiritual ecstasy.",
      "I believe a spiritual partner is a mirror reflecting the Divine's beautiful names. Sincerity is key.",
      "Calligraphy is my form of meditation. When I write the sacred names, my mind becomes completely still."
    ]
  },
  {
    id: "sp-4",
    name: "Gurpreet Singh",
    age: 27,
    gender: "Male",
    height: "6'2\"",
    location: "Amritsar, Punjab",
    religion: "Sikhism",
    sect: "Amritdhari (Khalsa)",
    caste: "Jat",
    subcaste: "Gill",
    spiritualPath: "Damdami Taksal (Gurmat)",
    deity: "Ik Onkar (One Universal Creator)",
    sadhana: "Early morning Amrit Vela prayers (Nitnem), Naam Simran, and active community kitchen (Langar) Seva.",
    diet: "Strict Lacto-Vegetarian (Langar diet)",
    profession: "Organic Farming Consultant",
    avatarColor: "from-amber-500 to-red-600",
    bio: "Living by the timeless principles of Guru Nanak: Kirat Karo (honest labor), Naam Japna (remembering the Creator), and Vand Chhako (sharing with others). Looking for a dedicated Gursikh partner.",
    hobbies: ["Gatka Martial Arts", "Playing Dilruba", "Sikh History", "Community Seva"],
    chatGreeting: "Waheguru Ji Ka Khalsa, Waheguru Ji Ki Fateh! 🙏 Blessed to connect with you. Wishing you high spirits (Chardi Kala)!",
    chatResponses: [
      "Waking up at Amrit Vela (3 AM) and meditating on Naam is the most peaceful part of my day.",
      "Seva (selfless service) is essential. It keeps us grounded and washes away the ego.",
      "I teach organic farming to help preserve mother earth (Pavan Guru Paani Pita). Nature is the directly visible form of Waheguru.",
      "The sound of the Dilruba playing Gurmat Sangeet brings absolute peace. Do you enjoy devotional music?"
    ]
  },
  {
    id: "sp-5",
    name: "Pranav Oswal",
    age: 30,
    gender: "Male",
    height: "5'8\"",
    location: "Mumbai, Maharashtra",
    religion: "Jainism",
    sect: "Svetambara",
    caste: "Oswal",
    subcaste: "Murtipujaka",
    spiritualPath: "Shrimad Rajchandra Mission",
    deity: "Lord Mahavira (24th Tirthankara)",
    sadhana: "Daily Samayik (48-min introspection), reciting the Navkar Mantra, study of Atma Siddhi scriptures.",
    diet: "Strict Jain Vegetarian (No Root Vegetables)",
    profession: "Ethical Venture Capitalist",
    avatarColor: "from-blue-400 to-indigo-500",
    bio: "Attempting to run a modern business anchored in absolute truth, non-violence (Ahimsa), and detachment (Aparigraha). I seek a partner with whom I can share the path of self-realization.",
    hobbies: ["Spiritual Literature", "Jivdaya (Animal Rescue)", "Yoga", "Trekking"],
    chatGreeting: "Jai Jinendra! 🙏 Wishing you peace and equanimity. May all living beings be happy.",
    chatResponses: [
      "Shrimad Rajchandra's writings show us how to be spiritual while living actively in the modern world.",
      "For me, Ahimsa is not just about diet, but also avoiding harsh words and judgmental thoughts.",
      "Every evening, I sit for a 48-minute Samayik to introspect and practice mindfulness. It resets my system.",
      "Ethical investing is my way of practicing corporate mindfulness. What kind of humanitarian work inspires you?"
    ]
  },
  {
    id: "sp-6",
    name: "Tenzin Choedon",
    age: 27,
    gender: "Female",
    height: "5'4\"",
    location: "Dharamshala, HP",
    religion: "Buddhism",
    sect: "Vajrayana (Tibetan)",
    caste: "Bhutia",
    subcaste: "Sherpa",
    spiritualPath: "Dalai Lama's Teachings / Vipassana",
    deity: "Gautama Buddha / Tara",
    sadhana: "Green Tara chanting, daily 45 minutes silent mindfulness meditation, and cultivating loving-kindness (Metta).",
    diet: "Lacto-Vegetarian",
    profession: "Mindfulness Therapist",
    avatarColor: "from-red-400 to-rose-600",
    bio: "Living in the lap of the Himalayas, my life is centered around mindfulness, compassion, and mental well-being. Looking for a partner who is kind-hearted and values emotional and spiritual intelligence.",
    hobbies: ["Thangka Painting", "Buddhist philosophy", "Mountain Hiking", "Volunteering"],
    chatGreeting: "Tashi Delek! 🌸 Sending you waves of loving-kindness and mindfulness. I hope you are present and peaceful today.",
    chatResponses: [
      "Mindfulness meditation is my anchor. It teaches us to witness our emotions without reacting.",
      "Living in Dharamshala, we are blessed with the presence of His Holiness. His teachings on warm-heartedness are my guide.",
      "I believe a happy relationship is based on two individuals who take responsibility for their own minds.",
      "I paint Thangkas (sacred Buddhist scrolls) as a form of active meditation. It requires intense focus and devotion."
    ]
  },
  {
    id: "sp-7",
    name: "Sarah D'Souza",
    age: 25,
    gender: "Female",
    height: "5'6\"",
    location: "Kochi, Kerala",
    religion: "Christianity",
    sect: "Syrian Catholic",
    caste: "Syrian Christian",
    subcaste: "Knanaya Catholic",
    spiritualPath: "Catholic Charismatic Renewal",
    deity: "Jesus Christ / Holy Spirit",
    sadhana: "Morning Eucharistic adoration, daily Bible study, evening Family Rosary, and choir service.",
    diet: "Non-Vegetarian (Prefers healthy, organic)",
    profession: "Pediatrician",
    avatarColor: "from-pink-400 to-rose-500",
    bio: "Compassionate, faith-driven, and family-oriented. I seek to put God at the center of my life and marriage. Looking for a practicing Christian who wants to raise a family rooted in love, prayer, and service.",
    hobbies: ["Choir Singing", "Playing Piano", "Community Health Camps", "Baking"],
    chatGreeting: "Praise the Lord! ✨ Wishing you grace, joy, and peace in your heart. How can I walk with you on this journey?",
    chatResponses: [
      "For me, faith is not just a Sunday ritual, but a living connection with the Divine in every action.",
      "Singing in the parish choir is my favorite way of praising the Lord. It feels like praying twice!",
      "I believe a marriage is a sacred covenant, built on mutual respect, selfless love, and shared prayers.",
      "Being a pediatrician, I see God's pure spark in every child. Healing them is my form of worship."
    ]
  },
  {
    id: "sp-8",
    name: "Karan Patel",
    age: 29,
    gender: "Male",
    height: "5'10\"",
    location: "Ahmedabad, Gujarat",
    religion: "Hinduism",
    sect: "Swaminarayan",
    caste: "Vaishya",
    subcaste: "Leva Patel",
    spiritualPath: "BAPS Swaminarayan Sanstha",
    deity: "Bhagwan Swaminarayan",
    sadhana: "Morning personal Puja, reading the Vachanamrut daily, and hosting weekly family Satsangs (Ghar Sabha).",
    diet: "Strict Vegetarian (No Onion/Garlic)",
    profession: "Eco-Building Consultant",
    avatarColor: "from-yellow-400 to-orange-500",
    bio: "Living a disciplined life guided by spiritual values, community service, and family cohesion. I seek a companion who values cultural roots and wants to build a home of peace, respect, and devotion.",
    hobbies: ["Temple Volunteering", "Organic Gardening", "Sustainable Designing", "Folk Music"],
    chatGreeting: "Jai Swaminarayan! 🙏 It is a pleasure to connect with a fellow seeker. May Maharaj bless your aspirations.",
    chatResponses: [
      "Ghar Sabha (family spiritual sharing) is an incredible tool. It keeps the family unified and peaceful.",
      "I volunteer at the Akshardham complex. Helping others selflessy is our Guru's key teaching.",
      "Sattvic diet keeps the mind calm and helps in deeper meditation. I would love to cook healthy, pure meals with my partner.",
      "Sustainable civil engineering is my way of respecting the divine creation of Mother Earth."
    ]
  }
];

if (typeof module !== "undefined" && module.exports) {
  module.exports = mockProfiles;
}
